package com.qy.springboot01.domain;

public class SysRolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_PERMISSION.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_PERMISSION.SYS_ROLE_ID
     *
     * @mbggenerated
     */
    private String sysRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_PERMISSION.SYS_PERMISSION_ID
     *
     * @mbggenerated
     */
    private String sysPermissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_PERMISSION.ID
     *
     * @return the value of SYS_ROLE_PERMISSION.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_PERMISSION.ID
     *
     * @param id the value for SYS_ROLE_PERMISSION.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_PERMISSION.SYS_ROLE_ID
     *
     * @return the value of SYS_ROLE_PERMISSION.SYS_ROLE_ID
     *
     * @mbggenerated
     */
    public String getSysRoleId() {
        return sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_PERMISSION.SYS_ROLE_ID
     *
     * @param sysRoleId the value for SYS_ROLE_PERMISSION.SYS_ROLE_ID
     *
     * @mbggenerated
     */
    public void setSysRoleId(String sysRoleId) {
        this.sysRoleId = sysRoleId == null ? null : sysRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_PERMISSION.SYS_PERMISSION_ID
     *
     * @return the value of SYS_ROLE_PERMISSION.SYS_PERMISSION_ID
     *
     * @mbggenerated
     */
    public String getSysPermissionId() {
        return sysPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_PERMISSION.SYS_PERMISSION_ID
     *
     * @param sysPermissionId the value for SYS_ROLE_PERMISSION.SYS_PERMISSION_ID
     *
     * @mbggenerated
     */
    public void setSysPermissionId(String sysPermissionId) {
        this.sysPermissionId = sysPermissionId == null ? null : sysPermissionId.trim();
    }
}