package com.qy.springboot01.domain;

public class SysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ROLE.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ROLE.SYS_USER_ID
     *
     * @mbggenerated
     */
    private String sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ROLE.SYS_ROLE_ID
     *
     * @mbggenerated
     */
    private String sysRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ROLE.ID
     *
     * @return the value of SYS_USER_ROLE.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ROLE.ID
     *
     * @param id the value for SYS_USER_ROLE.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ROLE.SYS_USER_ID
     *
     * @return the value of SYS_USER_ROLE.SYS_USER_ID
     *
     * @mbggenerated
     */
    public String getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ROLE.SYS_USER_ID
     *
     * @param sysUserId the value for SYS_USER_ROLE.SYS_USER_ID
     *
     * @mbggenerated
     */
    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId == null ? null : sysUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ROLE.SYS_ROLE_ID
     *
     * @return the value of SYS_USER_ROLE.SYS_ROLE_ID
     *
     * @mbggenerated
     */
    public String getSysRoleId() {
        return sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ROLE.SYS_ROLE_ID
     *
     * @param sysRoleId the value for SYS_USER_ROLE.SYS_ROLE_ID
     *
     * @mbggenerated
     */
    public void setSysRoleId(String sysRoleId) {
        this.sysRoleId = sysRoleId == null ? null : sysRoleId.trim();
    }
}